/**
 * Route visibility per role.
 *
 * This is a UX layer only — it decides what a role can see and navigate to.
 * The API enforces the real thing in `backend/src/auth/permissions.js`;
 * keep the two in step when you add a module.
 */
const TENANT_ADMIN_ROUTES = [
  '/dashboard',
  '/students',
  '/attendance',
  '/exams',
  '/lms',
  '/programs',
  '/certifications',
  '/admissions',
  '/leads',
  '/scholarships',
  '/referrals',
  '/documents',
  '/transport',
  '/hostel',
  '/library',
  '/inventory',
  '/payroll',
  '/video-classes',
  '/reports-builder',
  '/biometric-attendance',
  '/timetable',
  '/homework',
  '/calendar',
  '/id-cards',
  '/communication',
  '/fees',
  '/reports',
  '/ai-tutor',
  '/career-path',
  '/performance-analysis',
  '/fee-recovery',
  '/leave',
  '/discipline',
  '/report-cards',
  '/visitors',
  '/facilities',
  '/alumni',
  '/ptm',
  '/quizzes',
  '/surveys',
  '/branches',
  '/gps-tracking',
  '/wallet',
  '/substitutes',
  '/health-records',
  '/early-warning',
  '/settings',
  '/profile',
];

export const ROLE_PERMISSIONS = {
  super_admin: [
    '/admin',
    '/dashboard',
    '/reports',
    '/settings',
    '/profile',
    '/performance-analysis',
  ],
  institution_admin: TENANT_ADMIN_ROUTES,
  principal: TENANT_ADMIN_ROUTES,

  teacher: [
    '/dashboard',
    '/students',
    '/attendance',
    '/timetable',
    '/homework',
    '/calendar',
    '/exams',
    '/report-cards',
    '/discipline',
    '/lms',
    '/programs',
    '/certifications',
    '/leave',
    '/facilities',
    '/ptm',
    '/quizzes',
    '/substitutes',
    '/early-warning',
    '/communication',
    '/ai-tutor',
    '/performance-analysis',
    '/profile',
  ],

  student: [
    '/dashboard',
    '/attendance',
    '/timetable',
    '/homework',
    '/calendar',
    '/exams',
    '/report-cards',
    '/quizzes',
    '/lms',
    '/programs',
    '/certifications',
    '/scholarships',
    '/documents',
    '/communication',
    '/ai-tutor',
    '/career-path',
    '/profile',
  ],

  parent: [
    '/dashboard',
    '/attendance',
    '/timetable',
    '/homework',
    '/calendar',
    '/exams',
    '/report-cards',
    '/ptm',
    '/communication',
    '/fees',
    '/scholarships',
    '/certifications',
    '/performance-analysis',
    '/profile',
  ],

  staff: [
    '/dashboard',
    '/students',
    '/admissions',
    '/leads',
    '/scholarships',
    '/referrals',
    '/alumni',
    '/documents',
    '/programs',
    '/transport',
    '/hostel',
    '/library',
    '/inventory',
    '/video-classes',
    '/biometric-attendance',
    '/discipline',
    '/visitors',
    '/facilities',
    '/leave',
    '/ptm',
    '/surveys',
    '/gps-tracking',
    '/wallet',
    '/health-records',
    '/substitutes',
    '/early-warning',
    '/calendar',
    '/communication',
    '/fees',
    '/reports',
    '/profile',
  ],
};

export function getRolePermissions(role = 'student') {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.student;
}

export function canAccessPath(role, pathname) {
  const permissions = getRolePermissions(role);
  return permissions.some((path) => pathname === path || pathname.startsWith(`${path}/`));
}

export function canManageTenantUsers(role) {
  return ['super_admin', 'institution_admin', 'principal'].includes(role);
}
